# Example runtime configuration for trend prediction service
# Save as runtime_config.yaml and pass to main.py

runtime:
  # Dashboard update settings
  update_interval_sec: 60          # Update dashboard every 60 seconds
  enable_background_timer: true    # Enable continuous updates when event queue is idle
  
  # Prediction parameters
  delta_hours: 2                   # Time window for predictions
  window_min: 60                   # Rolling window in minutes
  k_default: 5                     # Default number of top predictions to show
  k_options: [3, 5, 10, 20]       # Available K options for dashboard
  
  # File paths (optional - will use defaults if not specified)
  # metrics_snapshot_dir: "./datasets/metrics"
  # predictions_cache_path: "./datasets/predictions_cache.json" 
  # topic_lookup_path: "./datasets/topic_lookup.json"

# Example usage:
# python src/service/main.py runtime_config.yaml

# Background Timer Feature:
# ========================
# When enable_background_timer: true (default):
#   - Dashboard updates continuously every update_interval_sec seconds
#   - Cache stays fresh even when event queue is idle
#   - Fixes stale dashboard issue during quiet periods
#
# When enable_background_timer: false:
#   - Dashboard only updates when processing events (original behavior)
#   - May become stale during idle periods
#   - Use only if you want minimal resource usage