runtime:
  # Quick configuration for latency testing
  update_interval_sec: 5  # Update metrics every 5 seconds for testing
  enable_background_timer: true
  metrics_snapshot_dir: "datasets/metrics_hourly"
  predictions_cache_path: "datasets/predictions_cache.json"
  topic_lookup_path: "datasets/topic_lookup.json"
  
  # Metrics configuration
  delta_hours: 2
  window_min: 60
  k_default: 5
  k_options: [5, 10]